### ISSUE TITLE
NameError: uninitialized constant DeviseMultipleTokenAuthDevice

### ISSUE THREAD

**Issue by vishalnagda1** [JoshJuncker/DeviseMultipleTokenAuth#3]
Hello Programmers & Developers!!!, I'm facing a problem in `rails console` when I tried to access `DeviseMultipleTokenAuthDevice` then I'm getting the following error :<br><br>

    Loading development environment (Rails 4.2.0)
    2.2.4 :001 > DeviseMultipleTokenAuthDevice
    NameError: uninitialized constant DeviseMultipleTokenAuthDevice
    	from (irb):1
    	from /Users/vishal/.rvm/gems/ruby-2.2.4@devise_demo/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
    	from /Users/vishal/.rvm/gems/ruby-2.2.4@devise_demo/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
    	from /Users/vishal/.rvm/gems/ruby-2.2.4@devise_demo/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
    	from /Users/vishal/.rvm/gems/ruby-2.2.4@devise_demo/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    	from /Users/vishal/.rvm/gems/ruby-2.2.4@devise_demo/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    	from script/rails:6:in `require'
    	from script/rails:6:in `<main>'
    2.2.4 :002 > 

<br><br>Following gems I'm using in my project for user authentication<br>

    gem 'devise'
    gem 'devise_multiple_token_auth'

<br>Following are the tables in my record :<br>

    2.2.4 :002 > p ActiveRecord::Base.connection.tables
    ["schema_migrations", "users", "devise_multiple_token_auth_devices"]
     => ["schema_migrations", "users", "devise_multiple_token_auth_devices"] 
    2.2.4 :003 >

<br>
**For more info you can follow these links :**

 - [Source from where I followed the instruction][1]
 - [My Github repo link for project source][2]

<br>Other required information<br>
**Ruby Version** `2.2.4`<br>
**Rails Version** `4.2.0`<br>
**Database** `PSQL`

  [1]: https://github.com/JoshJuncker/DeviseMultipleTokenAuth
  [2]: https://github.com/vishalnagda1/devise_demo/tree/staging

**Comment by vishalnagda1** [comment]
The solution for the same is, we've to create a file called `devise_multiple_token_auth_device.rb` in app/models/

<br>**here is the code for *devise_multiple_token_auth_device.rb* file**<br>

    class DeviseMultipleTokenAuthDevice < ActiveRecord::Base
      belongs_to :user
    end
